apiVersion: v1
kind: Pod
metadata:
  name: tensorflow
  labels:
    app: mnist
    framework: tensorflow
spec:
  restartPolicy: OnFailure
  containers:
  - name: tensorflow 
    image: rgaut/deeplearning-tensorflow:with_model 
    command:
      - "python"
      - "/tmp/models/official/mnist/mnist.py --export_dir /model/"
