apiVersion: v1
kind: Pod
metadata:
  name: mxnet-mnist
  labels:
    app: mxnet
spec:
  restartPolicy: OnFailure
  containers:
  - name: mxnet-mnist
    image: rgaut/deeplearning-mxnet:with_mnist_cnn_gpu
    command: 
      - "python"
      - "/tmp/mnist_cnn.py"
    volumeMounts:
    - mountPath: /mxnet
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /mnist_model
       
