apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorboard-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tensorboard
    spec:
      containers:
      - name: tensorboard-demo-container
        image: rgaut/tensorboard:latest
        command: ["/bin/sh", "-c", "tensorboard --logdir /root/graphs --port 6006"]
        ports:
        - containerPort: 6006
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: tensorboard
  name: tensorboard 
spec:
  ports:
  - port: 6006
    targetPort: 6006
  selector:
    app: tensorboard
  type: LoadBalancer
